theme: jekyll-theme-cayman
title: The Undocumented Analysts
description: First draft of our website
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Section
    url: /
  - title: Example
    url: example
